[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/chess-theme-classifier/train-isc.py", line 312, in <module>
[rank0]:     main(args, timer)
[rank0]:   File "/root/chess-theme-classifier/train-isc.py", line 167, in main
[rank0]:     for batch_data in train_dataloader:
[rank0]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
[rank0]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank0]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank0]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank0]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/root/chess-theme-classifier/dataset.py", line 664, in __getitem__
[rank0]:     board_tensor = self.tensor_cache[idx].to(dtype=torch.float32)
[rank0]: IndexError: list index out of range
[rank2]: Traceback (most recent call last):
[rank2]:   File "/root/chess-theme-classifier/train-isc.py", line 312, in <module>
[rank2]:     main(args, timer)
[rank2]:   File "/root/chess-theme-classifier/train-isc.py", line 167, in main
[rank2]:     for batch_data in train_dataloader:
[rank2]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank2]:     data = self._next_data()
[rank2]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
[rank2]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank2]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank2]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank2]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank2]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank2]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank2]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank2]:   File "/root/chess-theme-classifier/dataset.py", line 664, in __getitem__
[rank2]:     board_tensor = self.tensor_cache[idx].to(dtype=torch.float32)
[rank2]: IndexError: list index out of range
[rank3]: Traceback (most recent call last):
[rank3]:   File "/root/chess-theme-classifier/train-isc.py", line 312, in <module>
[rank3]:     main(args, timer)
[rank3]:   File "/root/chess-theme-classifier/train-isc.py", line 167, in main
[rank3]:     for batch_data in train_dataloader:
[rank3]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank3]:     data = self._next_data()
[rank3]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
[rank3]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank3]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank3]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank3]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank3]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank3]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank3]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank3]:   File "/root/chess-theme-classifier/dataset.py", line 664, in __getitem__
[rank3]:     board_tensor = self.tensor_cache[idx].to(dtype=torch.float32)
[rank3]: IndexError: list index out of range
[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/chess-theme-classifier/train-isc.py", line 312, in <module>
[rank1]:     main(args, timer)
[rank1]:   File "/root/chess-theme-classifier/train-isc.py", line 167, in main
[rank1]:     for batch_data in train_dataloader:
[rank1]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank1]:     data = self._next_data()
[rank1]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
[rank1]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank1]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank1]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank1]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank1]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank1]:   File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank1]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank1]:   File "/root/chess-theme-classifier/dataset.py", line 664, in __getitem__
[rank1]:     board_tensor = self.tensor_cache[idx].to(dtype=torch.float32)
[rank1]: IndexError: list index out of range
W0604 03:06:21.325000 140037615247360 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 62 closing signal SIGTERM
W0604 03:06:21.325000 140037615247360 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 64 closing signal SIGTERM
W0604 03:06:21.325000 140037615247360 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 65 closing signal SIGTERM
E0604 03:06:21.539000 140037615247360 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 63) of binary: /root/chess-theme-classifier/.chess-theme-classifier/bin/python3
Traceback (most recent call last):
  File "/root/chess-theme-classifier/.chess-theme-classifier/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/chess-theme-classifier/.chess-theme-classifier/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train-isc.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-04_03:06:21
  host      : sc5
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 63)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================